version: '3'
networks:
  gostsclient:
    driver: bridge
services:
   mysql:
     image: mysql:5.5
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=sts
       - MYSQL_USER=sts
       - MYSQL_PASSWORD=sts123
     networks:
       - gostsclient
   sts:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/sts-frontend:543492665993a4323f1d4fc94d266278d58764fb
     environment:
       - SERVER_NAME=sts
       - STS_HOST=sts-backend
     volumes:
       - ./sts/sts.cer:/certificates/sts.cer
       - ./sts/sts.pem:/certificates/sts.pem
     networks:
       - gostsclient
   sts-backend:
     image: kitdocker.kvalitetsit.dk/kvalitetsit/sts:543492665993a4323f1d4fc94d266278d58764fb
     environment:
       - LOG_LEVEL=DEBUG
       - STS_ISSUER=stsa
       - STS_TOKEN_LIFETIME=2800
       - STS_SUPPORTED_CLAIMS=claim-a,claim-b
       - STS_COPY_ATTRIBUTES=claim-a
       - STS_CERTIFICATE=/certificates/sts.cer
       - STS_KEY=/certificates/sts.pem
       - STS_TRUST_CA_PATH=/trust/*
       - MYSQL_HOST=mysql
       - MYSQL_DBNAME=sts
       - MYSQL_USERNAME=sts
       - MYSQL_PASSWORD=sts123
       - JSON_CLIENT_PATH=/clients/clients.json
     volumes:
       - ./sts/sts.cer:/certificates/sts.cer
       - ./sts/sts.pem:/certificates/sts.pem
       - ./sts/clients:/clients
     networks:
       - gostsclient

